# This workflow automatically merges pull requests from exercism-solutions-syncer

name: Automerge Exercism Solutions

on:
  # Triggers the workflow when a pull request is opened, synchronized, or reopened
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    
    # This is the key condition: only run the job if the PR author is the syncer bot
    if: github.actor == 'exercism-solutions-syncer'
    
    steps:
      - name: Enable Automerge
        # This popular action enables GitHub's native auto-merge feature
        uses: pascalgn/automerge-action@v0.16.2
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # You can change the merge method to 'merge' or 'rebase' if you prefer
          MERGE_METHOD: "squash"
