# TEMPORARY DEBUGGING WORKFLOW
name: Automerge Exercism Solutions

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Debug: Print GitHub context'
        run: echo "${{ toJSON(github) }}"
