name: Automerge Exercism Solutions

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'exercism-solutions-syncer[bot]'
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Enable Automerge
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: ""
